version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/go/src/git.furqansoftware.net/faqapp/faqapp
    depends_on:
      - mongo
    links:
      - mongo
    working_dir: /go/src/git.furqansoftware.net/faqapp/faqapp
    command: ./faqappd

  mongo:
    image: mongo:3.2
    volumes:
      - mongo:/data/db

  mongoexpress:
    image: mongo-express
    ports:
      - "5831:8081"
    depends_on:
      - mongo
    links:
      - mongo

volumes:
  mongo:
    driver: "local"
